USE movies;

--2020-lqto

--4a)
SELECT DISTINCT ms.NAME,ms.BIRTHDATE
FROM MOVIESTAR as ms 
JOIN STARSIN as si on ms.NAME=si.STARNAME
JOIN MOVIE as m on si.MOVIETITLE=m.TITLE
WHERE ms.NAME NOT LIKE '%Jr%'
and ms.NAME IN (SELECT DISTINCT si.STARNAME
				FROM STARSIN as si
				JOIN MOVIE as m on si.MOVIETITLE=m.TITLE
				WHERE m.INCOLOR='Y')
ORDER BY  ms.BIRTHDATE DESC, ms.NAME

--4b)



SELECT DISTINCT ms.NAME,YEAR(ms.BIRTHDATE) as year_ , COUNT(DISTINCT m.STUDIONAME) as cnt_studios
FROM MOVIESTAR as ms 
LEFT JOIN STARSIN as si on ms.NAME=si.STARNAME
LEFT JOIN MOVIE as m on si.MOVIETITLE=m.TITLE
WHERE ms.GENDER='F'
GROUP BY ms.NAME,ms.BIRTHDATE
HAVING COUNT(DISTINCT m.TITLE) <= 6
