[package]
name = "exercise_17_10"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
simple-matrix = { version = "0.1", features = ["impl_from"] }
